name = "docs"
main = ".open-next/worker.js"

compatibility_date = "2024-10-05"
compatibility_flags = ["nodejs_compat"]

assets = { directory = ".open-next/assets", binding = "ASSETS" }

workers_dev = false
routes = [{ pattern = "docs.icssc.club", custom_domain = true }]
