name = "docs"
main = ".worker-next/index.mjs"

compatibility_date = "2024-10-05"
compatibility_flags = ["nodejs_compat"]

assets = { directory = ".worker-next/assets", binding = "ASSETS" }

workers_dev = false
routes = [{ pattern = "docs.icssc.club", custom_domain = true }]

[alias]
"prettier" = "./node_modules/prettier/standalone.js"
